# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Config.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets, QtGui
from Scripts.Utils import get_config_path, resource_path
import json
import functools

class Config_Ui(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(460, 580)
        Dialog.setMinimumSize(420, 500)
        Dialog.setStyleSheet(
            "QDialog { background-color: #F0F2F5; }"
            "QScrollArea { background: transparent; border: none; }"
            "QScrollArea > QWidget > QWidget { background: transparent; }"
            "QScrollBar:vertical { background: #F0F2F5; width: 8px; border-radius: 4px; }"
            "QScrollBar::handle:vertical { background: #D1D5DB; border-radius: 4px; min-height: 30px; }"
            "QScrollBar::handle:vertical:hover { background: #9CA3AF; }"
            "QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical { height: 0px; }"
            "QCheckBox { color: #374151; font: 10pt \"Microsoft YaHei\"; spacing: 8px; }"
            "QCheckBox::indicator { width: 18px; height: 18px; border-radius: 4px; "
            "border: 2px solid #D1D5DB; background-color: #FFFFFF; }"
            "QCheckBox::indicator:checked { background-color: #4A6CF7; border-color: #4A6CF7; }"
            "QCheckBox::indicator:hover { border-color: #4A6CF7; }"
            "QRadioButton { color: #374151; font: 10pt \"Microsoft YaHei\"; spacing: 8px; }"
            "QRadioButton::indicator { width: 18px; height: 18px; border-radius: 9px; "
            "border: 2px solid #D1D5DB; background-color: #FFFFFF; }"
            "QRadioButton::indicator:checked { background-color: #4A6CF7; border-color: #4A6CF7; }"
            "QRadioButton::indicator:hover { border-color: #4A6CF7; }"
            "QSpinBox { background-color: #FFFFFF; color: #1F2937; border: 1px solid #D1D5DB; "
            "border-radius: 6px; padding: 6px 10px; font: 10pt \"Microsoft YaHei\"; min-height: 20px; }"
            "QSpinBox:hover { border-color: #4A6CF7; }"
            "QSpinBox:focus { border-color: #4A6CF7; }"
            "QLineEdit { background-color: #FFFFFF; color: #1F2937; border: 1px solid #D1D5DB; "
            "border-radius: 6px; padding: 8px 10px; font: 10pt \"Microsoft YaHei\"; }"
            "QLineEdit:hover { border-color: #4A6CF7; }"
            "QLineEdit:focus { border-color: #4A6CF7; }"
            "QComboBox { background-color: #FFFFFF; color: #1F2937; border: 1px solid #D1D5DB; "
            "border-radius: 6px; padding: 8px 10px; font: 10pt \"Microsoft YaHei\"; min-height: 20px; }"
            "QComboBox:hover { border-color: #4A6CF7; }"
            "QComboBox:focus { border-color: #4A6CF7; }"
            "QComboBox::drop-down { border: none; width: 24px; }"
            "QComboBox QAbstractItemView { background-color: #FFFFFF; border: 1px solid #E5E7EB; "
            "border-radius: 4px; selection-background-color: #EEF2FF; selection-color: #1F2937; }"
            "QLabel { color: #4B5563; font: 10pt \"Microsoft YaHei\"; background: transparent; }"
        )
        Dialog.setWindowIcon(QtGui.QIcon(resource_path("UI\\Image\\favicon.ico")))
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -56, 393, 580))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_12.setContentsMargins(4, 8, 4, 8)
        self.verticalLayout_12.setSpacing(12)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.danmu_config = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.danmu_config.setStyleSheet(
            "QGroupBox {"
            "background-color: #FFFFFF;"
            "border: 1px solid #E5E7EB;"
            "border-radius: 10px;"
            "margin-top: 14px;"
            "padding: 16px 12px 12px 12px;"
            "font: 11pt \"Microsoft YaHei\";"
            "font-weight: bold;"
            "color: #1F2937;"
            "}"
            "QGroupBox::title {"
            "subcontrol-origin: margin;"
            "left: 14px;"
            "padding: 0 6px;"
            "}"
        )
        self.danmu_config.setObjectName("danmu_config")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.danmu_config)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.danmu_on = QtWidgets.QCheckBox(self.danmu_config)
        self.danmu_on.setObjectName("danmu_on")
        self.verticalLayout_2.addWidget(self.danmu_on)
        self.when_danmu_on = QtWidgets.QWidget(self.danmu_config)
        self.when_danmu_on.setEnabled(False)
        self.when_danmu_on.setObjectName("when_danmu_on")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.when_danmu_on)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.when_danmu_on)
        self.label.setScaledContents(False)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.danmu_spinBox = QtWidgets.QSpinBox(self.when_danmu_on)
        self.danmu_spinBox.setMaximum(32767)
        self.danmu_spinBox.setProperty("value", 5)
        self.danmu_spinBox.setObjectName("danmu_spinBox")
        self.verticalLayout_3.addWidget(self.danmu_spinBox)
        self.verticalLayout_2.addWidget(self.when_danmu_on)
        self.verticalLayout_12.addWidget(self.danmu_config)
        self.audio_config = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.audio_config.setStyleSheet(
            "QGroupBox {"
            "background-color: #FFFFFF;"
            "border: 1px solid #E5E7EB;"
            "border-radius: 10px;"
            "margin-top: 14px;"
            "padding: 16px 12px 12px 12px;"
            "font: 11pt \"Microsoft YaHei\";"
            "font-weight: bold;"
            "color: #1F2937;"
            "}"
            "QGroupBox::title {"
            "subcontrol-origin: margin;"
            "left: 14px;"
            "padding: 0 6px;"
            "}"
        )
        self.audio_config.setObjectName("audio_config")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.audio_config)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.audio_on = QtWidgets.QCheckBox(self.audio_config)
        self.audio_on.setObjectName("audio_on")
        self.verticalLayout_4.addWidget(self.audio_on)
        self.when_audio_on = QtWidgets.QWidget(self.audio_config)
        self.when_audio_on.setEnabled(False)
        self.when_audio_on.setObjectName("when_audio_on")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.when_audio_on)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.widget_4 = QtWidgets.QWidget(self.when_audio_on)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_11.setContentsMargins(9, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_4 = QtWidgets.QLabel(self.widget_4)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_11.addWidget(self.label_4)
        self.verticalLayout_10.addWidget(self.widget_4)
        self.widget_3 = QtWidgets.QWidget(self.when_audio_on)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.when_audio_on_1 = QtWidgets.QWidget(self.widget_3)
        self.when_audio_on_1.setObjectName("when_audio_on_1")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.when_audio_on_1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.self_danmu = QtWidgets.QCheckBox(self.when_audio_on_1)
        self.self_danmu.setObjectName("self_danmu")
        self.verticalLayout_7.addWidget(self.self_danmu)
        self.others_danmu = QtWidgets.QCheckBox(self.when_audio_on_1)
        self.others_danmu.setObjectName("others_danmu")
        self.verticalLayout_7.addWidget(self.others_danmu)
        self.receive_problem = QtWidgets.QCheckBox(self.when_audio_on_1)
        self.receive_problem.setObjectName("receive_problem")
        self.verticalLayout_7.addWidget(self.receive_problem)
        self.answer_result = QtWidgets.QCheckBox(self.when_audio_on_1)
        self.answer_result.setObjectName("answer_result")
        self.verticalLayout_7.addWidget(self.answer_result)
        self.horizontalLayout_4.addWidget(self.when_audio_on_1)
        self.when_audio_on_2 = QtWidgets.QWidget(self.widget_3)
        self.when_audio_on_2.setObjectName("when_audio_on_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.when_audio_on_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.self_called = QtWidgets.QCheckBox(self.when_audio_on_2)
        self.self_called.setObjectName("self_called")
        self.verticalLayout_6.addWidget(self.self_called)
        self.others_called = QtWidgets.QCheckBox(self.when_audio_on_2)
        self.others_called.setObjectName("others_called")
        self.verticalLayout_6.addWidget(self.others_called)
        self.course = QtWidgets.QCheckBox(self.when_audio_on_2)
        self.course.setObjectName("course")
        self.verticalLayout_6.addWidget(self.course)
        self.network = QtWidgets.QCheckBox(self.when_audio_on_2)
        self.network.setObjectName("network")
        self.verticalLayout_6.addWidget(self.network)
        self.horizontalLayout_4.addWidget(self.when_audio_on_2)
        self.verticalLayout_10.addWidget(self.widget_3)
        self.verticalLayout_4.addWidget(self.when_audio_on)
        self.verticalLayout_12.addWidget(self.audio_config)
        self.answer_config = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.answer_config.setStyleSheet(
            "QGroupBox {"
            "background-color: #FFFFFF;"
            "border: 1px solid #E5E7EB;"
            "border-radius: 10px;"
            "margin-top: 14px;"
            "padding: 16px 12px 12px 12px;"
            "font: 11pt \"Microsoft YaHei\";"
            "font-weight: bold;"
            "color: #1F2937;"
            "}"
            "QGroupBox::title {"
            "subcontrol-origin: margin;"
            "left: 14px;"
            "padding: 0 6px;"
            "}"
        )
        self.answer_config.setObjectName("answer_config")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.answer_config)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.answer_on = QtWidgets.QCheckBox(self.answer_config)
        self.answer_on.setObjectName("answer_on")
        self.verticalLayout_5.addWidget(self.answer_on)
        self.when_answer_on = QtWidgets.QWidget(self.answer_config)
        self.when_answer_on.setEnabled(False)
        self.when_answer_on.setObjectName("when_answer_on")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.when_answer_on)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_3 = QtWidgets.QLabel(self.when_answer_on)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_8.addWidget(self.label_3)
        self.delay_time_radio_1 = QtWidgets.QRadioButton(self.when_answer_on)
        self.delay_time_radio_1.setChecked(True)
        self.delay_time_radio_1.setObjectName("delay_time_radio_1")
        self.verticalLayout_8.addWidget(self.delay_time_radio_1)
        self.delay_time_radio_2 = QtWidgets.QRadioButton(self.when_answer_on)
        self.delay_time_radio_2.setObjectName("delay_time_radio_2")
        self.verticalLayout_8.addWidget(self.delay_time_radio_2)
        self.when_delay_time_2 = QtWidgets.QWidget(self.when_answer_on)
        self.when_delay_time_2.setEnabled(False)
        self.when_delay_time_2.setObjectName("when_delay_time_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.when_delay_time_2)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 3)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.delay_time_2_input = QtWidgets.QSpinBox(self.when_delay_time_2)
        self.delay_time_2_input.setObjectName("delay_time_2_input")
        self.verticalLayout_9.addWidget(self.delay_time_2_input)
        self.label_2 = QtWidgets.QLabel(self.when_delay_time_2)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_9.addWidget(self.label_2)
        self.verticalLayout_8.addWidget(self.when_delay_time_2)
        self.verticalLayout_5.addWidget(self.when_answer_on)
        self.verticalLayout_12.addWidget(self.answer_config)
        self.deepseek_config = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.deepseek_config.setStyleSheet(
            "QGroupBox {"
            "background-color: #FFFFFF;"
            "border: 1px solid #E5E7EB;"
            "border-radius: 10px;"
            "margin-top: 14px;"
            "padding: 16px 12px 12px 12px;"
            "font: 11pt \"Microsoft YaHei\";"
            "font-weight: bold;"
            "color: #1F2937;"
            "}"
            "QGroupBox::title {"
            "subcontrol-origin: margin;"
            "left: 14px;"
            "padding: 0 6px;"
            "}"
        )
        self.deepseek_config.setObjectName("deepseek_config")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.deepseek_config)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.deepseek_on = QtWidgets.QCheckBox(self.deepseek_config)
        self.deepseek_on.setObjectName("deepseek_on")
        self.verticalLayout_15.addWidget(self.deepseek_on)
        self.when_deepseek_on = QtWidgets.QWidget(self.deepseek_config)
        self.when_deepseek_on.setEnabled(False)
        self.when_deepseek_on.setObjectName("when_deepseek_on")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.when_deepseek_on)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.ds_key_label = QtWidgets.QLabel(self.when_deepseek_on)
        self.ds_key_label.setObjectName("ds_key_label")
        self.verticalLayout_13.addWidget(self.ds_key_label)
        self.ds_api_key = QtWidgets.QLineEdit(self.when_deepseek_on)
        self.ds_api_key.setEchoMode(QtWidgets.QLineEdit.Password)
        self.ds_api_key.setPlaceholderText("sk-...")
        self.ds_api_key.setObjectName("ds_api_key")
        self.verticalLayout_13.addWidget(self.ds_api_key)
        self.ds_timeout_label = QtWidgets.QLabel(self.when_deepseek_on)
        self.ds_timeout_label.setObjectName("ds_timeout_label")
        self.verticalLayout_13.addWidget(self.ds_timeout_label)
        self.ds_timeout_spin = QtWidgets.QSpinBox(self.when_deepseek_on)
        self.ds_timeout_spin.setMinimum(5)
        self.ds_timeout_spin.setMaximum(60)
        self.ds_timeout_spin.setValue(15)
        self.ds_timeout_spin.setSuffix(" 秒")
        self.ds_timeout_spin.setObjectName("ds_timeout_spin")
        self.verticalLayout_13.addWidget(self.ds_timeout_spin)
        self.ds_model_label = QtWidgets.QLabel(self.when_deepseek_on)
        self.ds_model_label.setObjectName("ds_model_label")
        self.verticalLayout_13.addWidget(self.ds_model_label)
        self.ds_model_combo = QtWidgets.QComboBox(self.when_deepseek_on)
        self.ds_model_combo.setEditable(True)
        self.ds_model_combo.addItems(["deepseek-v4-pro", "deepseek-chat", "deepseek-reasoner"])
        self.ds_model_combo.setObjectName("ds_model_combo")
        self.verticalLayout_13.addWidget(self.ds_model_combo)
        self.ds_note = QtWidgets.QLabel(self.when_deepseek_on)
        self.ds_note.setWordWrap(True)
        self.ds_note.setObjectName("ds_note")
        self.verticalLayout_13.addWidget(self.ds_note)
        self.verticalLayout_15.addWidget(self.when_deepseek_on)
        self.verticalLayout_12.addWidget(self.deepseek_config)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.btn_wid = QtWidgets.QWidget(Dialog)
        self.btn_wid.setObjectName("btn_wid")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.btn_wid)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.save = QtWidgets.QPushButton(self.btn_wid)
        self.save.setMinimumHeight(40)
        self.save.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.save.setStyleSheet(
            "QPushButton {"
            "background-color: #4A6CF7;"
            "color: #FFFFFF;"
            "border: none;"
            "border-radius: 8px;"
            "font: 10pt \"Microsoft YaHei\";"
            "font-weight: bold;"
            "padding: 10px 20px;"
            "}"
            "QPushButton:hover {"
            "background-color: #3B5DE7;"
            "}"
            "QPushButton:pressed {"
            "background-color: #2E4FD4;"
            "}"
        )
        self.save.setObjectName("save")
        self.horizontalLayout.addWidget(self.save)
        self.cancel = QtWidgets.QPushButton(self.btn_wid)
        self.cancel.setMinimumHeight(40)
        self.cancel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancel.setStyleSheet(
            "QPushButton {"
            "background-color: #FFFFFF;"
            "color: #6B7280;"
            "border: 1px solid #D1D5DB;"
            "border-radius: 8px;"
            "font: 10pt \"Microsoft YaHei\";"
            "padding: 10px 20px;"
            "}"
            "QPushButton:hover {"
            "background-color: #F9FAFB;"
            "border-color: #9CA3AF;"
            "}"
            "QPushButton:pressed {"
            "background-color: #F3F4F6;"
            "}"
        )
        self.cancel.setObjectName("cancel")
        self.horizontalLayout.addWidget(self.cancel)
        self.verticalLayout.addWidget(self.btn_wid)

        # 动作绑定
        self.cancel.clicked.connect(Dialog.reject)
        self.danmu_on.stateChanged.connect(self.enable_danmu_config)
        self.audio_on.stateChanged.connect(self.enable_audio_config)
        self.answer_on.stateChanged.connect(self.enable_answer_config)
        self.delay_time_radio_1.clicked.connect(self.enable_delay_custom)
        self.delay_time_radio_2.clicked.connect(self.enable_delay_custom)
        self.deepseek_on.stateChanged.connect(self.enable_deepseek_config)
        self.save.clicked.connect(functools.partial(self.save_config,dialog=Dialog))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def enable_danmu_config(self):
        # 启用自动弹幕详细配置Widget
        if self.danmu_on.isChecked():
            self.when_danmu_on.setEnabled(True)
        else:   
            self.when_danmu_on.setEnabled(False)

    def enable_audio_config(self):
        # 启用语言提醒详细配置Widget
        if self.audio_on.isChecked():
            self.when_audio_on.setEnabled(True)
        else:   
            self.when_audio_on.setEnabled(False)
    
    def enable_answer_config(self):
        # 启用自动答题详细配置Widget
        if self.answer_on.isChecked():
            self.when_answer_on.setEnabled(True)
        else:   
            self.when_answer_on.setEnabled(False)

    def enable_delay_custom(self):
        # 启用自定义延迟详细配置Widget
        if self.delay_time_radio_2.isChecked():
            self.when_delay_time_2.setEnabled(True)
        else:
            self.when_delay_time_2.setEnabled(False)

    def enable_deepseek_config(self):
        # 启用DeepSeek详细配置Widget
        if self.deepseek_on.isChecked():
            self.when_deepseek_on.setEnabled(True)
        else:
            self.when_deepseek_on.setEnabled(False)

    def load_config(self, config):
        # 弹幕配置
        self.danmu_on.setChecked(config["auto_danmu"])
        self.danmu_spinBox.setValue(config["danmu_config"]["danmu_limit"])
        # 语音配置
        self.audio_on.setChecked(config["audio_on"])
        self.self_danmu.setChecked(config["audio_config"]["audio_type"]["send_danmu"])
        self.others_danmu.setChecked(config["audio_config"]["audio_type"]["others_danmu"])
        self.receive_problem.setChecked(config["audio_config"]["audio_type"]["receive_problem"])
        self.answer_result.setChecked(config["audio_config"]["audio_type"]["answer_result"])
        self.self_called.setChecked(config["audio_config"]["audio_type"]["im_called"])
        self.others_called.setChecked(config["audio_config"]["audio_type"]["others_called"])
        self.course.setChecked(config["audio_config"]["audio_type"]["course_info"])
        self.network.setChecked(config["audio_config"]["audio_type"]["network_info"])
        # 答题配置
        self.answer_on.setChecked(config["auto_answer"])
        if config["answer_config"]["answer_delay"]["type"] == 1:
            self.delay_time_radio_1.setChecked(True)
        elif config["answer_config"]["answer_delay"]["type"] == 2:
            self.delay_time_radio_2.setChecked(True)
        self.delay_time_2_input.setValue(config["answer_config"]["answer_delay"]["custom"]["time"])
        # DeepSeek配置
        deepseek_cfg = config.get("deepseek_config", {})
        self.deepseek_on.setChecked(deepseek_cfg.get("enabled", False))
        self.ds_api_key.setText(deepseek_cfg.get("api_key", ""))
        self.ds_timeout_spin.setValue(deepseek_cfg.get("timeout", 15))
        self.ds_model_combo.setCurrentText(deepseek_cfg.get("model", "deepseek-chat"))
        self.dialog_config = config

    def save_config(self, dialog):
        config = self.dialog_config
        # 弹幕配置
        config["auto_danmu"] = self.danmu_on.isChecked()
        config["danmu_config"]["danmu_limit"] = self.danmu_spinBox.value()
        # 语音配置
        config["audio_on"] = self.audio_on.isChecked()
        config["audio_config"]["audio_type"]["send_danmu"] = self.self_danmu.isChecked()
        config["audio_config"]["audio_type"]["others_danmu"] = self.others_danmu.isChecked()
        config["audio_config"]["audio_type"]["receive_problem"] = self.receive_problem.isChecked()
        config["audio_config"]["audio_type"]["answer_result"] = self.answer_result.isChecked()
        config["audio_config"]["audio_type"]["im_called"] = self.self_called.isChecked()
        config["audio_config"]["audio_type"]["others_called"] = self.others_called.isChecked()
        config["audio_config"]["audio_type"]["course_info"] = self.course.isChecked()
        config["audio_config"]["audio_type"]["network_info"] = self.network.isChecked()
        # 答题配置
        config["auto_answer"] = self.answer_on.isChecked()
        if self.delay_time_radio_1.isChecked():
            config["answer_config"]["answer_delay"]["type"] = 1
        elif self.delay_time_radio_2.isChecked():
            config["answer_config"]["answer_delay"]["type"] = 2
        config["answer_config"]["answer_delay"]["custom"]["time"] = self.delay_time_2_input.value()
        # DeepSeek配置
        ds_cfg = config.get("deepseek_config", {})
        ds_cfg["enabled"] = self.deepseek_on.isChecked()
        ds_cfg["api_key"] = self.ds_api_key.text()
        ds_cfg["timeout"] = self.ds_timeout_spin.value()
        ds_cfg["model"] = self.ds_model_combo.currentText()
        config["deepseek_config"] = ds_cfg
        # 保存
        config_path = get_config_path()
        with open(config_path,"w+") as f:
            json.dump(config,f)
        dialog.accept()

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "配置"))
        self.danmu_config.setTitle(_translate("Dialog", "弹幕配置"))
        self.danmu_on.setText(_translate("Dialog", "启用自动发送弹幕"))
        self.label.setText(_translate("Dialog", "自动弹幕阈值（每分钟内收到n条弹幕后自动发送相同弹幕）"))
        self.audio_config.setTitle(_translate("Dialog", "语音配置"))
        self.audio_on.setText(_translate("Dialog", "启用语音提醒"))
        self.label_4.setText(_translate("Dialog", "需要语音提醒的内容"))
        self.self_danmu.setText(_translate("Dialog", "自动发送弹幕情况提醒"))
        self.others_danmu.setText(_translate("Dialog", "他人弹幕发送语音提醒"))
        self.receive_problem.setText(_translate("Dialog", "收到题目提醒"))
        self.answer_result.setText(_translate("Dialog", "自动答题情况提醒"))
        self.self_called.setText(_translate("Dialog", "自己被点名提醒"))
        self.others_called.setText(_translate("Dialog", "他人被点名提醒"))
        self.course.setText(_translate("Dialog", "课程相关提醒"))
        self.network.setText(_translate("Dialog", "网络断开/重连提醒"))
        self.answer_config.setTitle(_translate("Dialog", "答题配置"))
        self.answer_on.setText(_translate("Dialog", "启用自动答题"))
        self.label_3.setText(_translate("Dialog", "答题延迟时长"))
        self.delay_time_radio_1.setText(_translate("Dialog", "系统默认（随机决定时间）"))
        self.delay_time_radio_2.setText(_translate("Dialog", "自定义（于收到题目n秒后自动回答）"))
        self.label_2.setText(_translate("Dialog", "注：如果您采用自定义延迟时长，当延迟时长大于题目所给时限时，将按照系统默认算法重新计算延迟时长。"))
        self.deepseek_config.setTitle(_translate("Dialog", "DeepSeek 智能答题"))
        self.deepseek_on.setText(_translate("Dialog", "启用 DeepSeek AI 辅助答题（当PPT无答案时自动调用）"))
        self.ds_key_label.setText(_translate("Dialog", "API 密钥："))
        self.ds_timeout_label.setText(_translate("Dialog", "请求超时："))
        self.ds_model_label.setText(_translate("Dialog", "模型选择："))
        self.ds_note.setText(_translate("Dialog", "提示：需要从 https://platform.deepseek.com/ 获取 API 密钥。密钥仅保存在本地配置文件中。"))
        self.save.setText(_translate("Dialog", "保存"))
        self.cancel.setText(_translate("Dialog", "取消"))
